agregado mAs automatico de Auto Time. Este se muestra cuando se regis…
cc5402-Mamografias/mamografsim pull request #115
Opened 2020-12-17 16:16 UTC by GCarboni96

…tran los resultados de la imagen. El valor base que tiene ahora es de 100 mAs

2020-12-17 23:21 UTC, AlphaSteam requested changes
Ya lo hablé con Gian, pero para que quede escrito.
Creo que es mejor cambiar el cuadro de texto de los mA y los botones para cambiarlos a disabled. En vez de borrar el número del cuadro de texto y poner un numero default al cambiar a otro modo.
Esto porque en la versión actual, una vez que se selecciona el modo autotime, nada evita que el usuario cambie el valor nuevamente. Además es confuso que se borre el valor que había puesto y se reemplace por otro.

2020-12-18 17:11 UTC, joseastorgat commented
Se rompieron los nombres de la seleccion de pruebas - aparecen todos en null, redirige bien a las pruebas de imagen y rendimiento pero no a la de compresioooon.

2020-12-18 17:13 UTC, joseastorgat reviewed
![image](https://user-images.githubusercontent.com/20688987/102641669-356ace00-413b-11eb-864b-5155e579dccd.png)

2020-12-18 17:30 UTC, joseastorgat commented
Mas informacion sobre esto:  El error sucede cuando me cambio a rama autotime-imagen y reinstalo el plugin. Si voy desde develop y compilo sin reinstalar no hay problema.

2020-12-18 17:37 UTC, joseastorgat approved these changes

2020-12-18 19:57 UTC, AlphaSteam approved these changes

2020-12-18 20:15 UTC, merged