Form
cc5402-Mamografias/mamografsim pull request #44
Opened 2020-10-30 23:54 UTC by AlphaSteam

2020-11-02 19:20 UTC, felipe-canales requested changes
Hay un par de cosas que hay que cambiar

2020-11-02 19:20 UTC, felipe-canales commented on amd/src/main.js
> +    this.mamografo = new Maquina(parseInt(errorkv),parseInt(errorma), parseInt(errorF),parseInt(errorAlt), this.ctx);
La altura se maneja internamente en **cm**, pero se pasa en **mm**

2020-11-02 19:20 UTC, felipe-canales commented on db/install.xml
> +        <FIELD NAME="errorf" TYPE="int" LENGTH="10" NOTNULL="false" DEFAULT="0" SEQUENCE="false" COMMENT="Error de fuerza mamografo."/>
el error de fuerza debería ser float

2020-11-03 15:23 UTC, GCarboni96 commented
Aparecen unos warnings de php cuando cargo el simulador. tambien en el formulario

2020-11-03 15:33 UTC, GCarboni96 approved these changes

2020-11-03 21:49 UTC, AlphaSteam commented
> Aparecen unos warnings de php cuando cargo el simulador. tambien en el formulario

Hay que desintalar e instalar el plugin por que se actualiza la base de datos

2020-11-03 21:51 UTC, AlphaSteam commented on amd/src/main.js
> +    this.mamografo = new Maquina(parseInt(errorkv),parseInt(errorma), parseInt(errorF),parseInt(errorAlt), this.ctx);
Por que lo manejamos en cm, que ventaja tiene?

2020-11-03 21:53 UTC, felipe-canales commented on amd/src/main.js
> +    this.mamografo = new Maquina(parseInt(errorkv),parseInt(errorma), parseInt(errorF),parseInt(errorAlt), this.ctx);
Ninguna, simplemente esta hecho así.
Habría que cambiar varias cosas si queremos pasar todo a mm.

2020-11-03 23:26 UTC, AlphaSteam commented
Sacar los errores de el arreglo que recibe. Es importante que reciba un arreglo por que si agregamos más errores, evita tener que reescribir código en múltiples scripts.

Se imprime en consola el arreglo de los errores para que sea más facil ver como sacar cada error. 
Se debe módificar lo del Json con respecto al branch. Para ello debe ser mergeado primero.

2020-11-05 13:12 UTC, felipe-canales approved these changes

2020-11-05 13:12 UTC, merged