Smooth2
cc5402-Mamografias/mamografsim pull request #82
Opened 2020-11-18 00:33 UTC by AlphaSteam

Cambiada la forma en que baja el mamógrafo, junto a las formulas usadas para la compresión y descompresión.
El mamógrafo baja de forma continua. Hay variables para la velocidad motorizada y manual (la manual debería ser menor o no?)
La formula está sujeta a cambios, deje como variables todos los parametros que la afectan. La formula es Math.log2(this.factorCompresion)*this.multCompresion + this.sumaCompresionManual. 
Cuando se sube el compresor, se descomprime con la misma formula, pero 5 veces más rápido.

2020-11-18 18:32 UTC, joseastorgat commented
- Me parece extraño el siguiente caso: 

- Cuando comprimo al máximo  y luego descomprimo, me marca una altura por ejemplo de 80mm y aun así me indica una fuerza de compresión >0 , es decir está comprimiendo pero no está tocando la balanza! 

- La balanza también marca esa fuerza, lo que claramente es un error. No estoy seguro si es un error el hecho de que el mamografo lo marque.

2020-11-18 22:05 UTC, felipe-canales requested changes

2020-11-18 22:05 UTC, felipe-canales commented on amd/src/maquina.js
> +    this.alturaCompresor += this.velocY;
Compresor no debería subir hasta que la fuerza sera cero.

2020-11-18 22:05 UTC, felipe-canales commented on amd/src/maquina.js
> +    this.alturaCompresor += this.velocYManual;
Compresor no debería subir hasta que la fuerza sera cero.

2020-11-19 18:25 UTC, AlphaSteam commented
Ya hice el cambio, para que lo vean

2020-11-30 13:37 UTC, felipe-canales approved these changes

2020-11-30 13:37 UTC, merged